#!/usr/bin/expect -f

set timeout 1

proc sendexpect { out in } {
	send $out
	expect {
		$in { puts "passed\n" }
		timeout { puts "***failed\n"; exit }
	}
}

# start the bc test
spawn bc
expect "warranty"

puts "Test Starting\n"

# test some simple math
send "2+6\n"
expect "8"

sendexpect "2+5\n" "7"

sendexpect  "2*9\n" "18"

sendexpect  "9-3\n" "6"


# test a simple function
sendexpect \
  "define f(x) { if(x<=1) return 1; return (f(x-1)*x);}\n" "\r"
sendexpect  "f(5)\n"  "120"

# end the test session
sendexpect  "quit\n" eof

puts "Test Complete\n"

exit
